# NumPy Basics

- Arrays, shape, size, data type
- Initializing Different Arrays (1s, 0s, full, random, etc...)
- Basic Mathematics (arithmetic, trigonometry, etc.)
- Linear Algebra
- Statistics
- Reorganizing Arrays (reshape, vstack, hstack)
- Load data in from a file
- Advanced Indexing and Boolean Masking

### About NumPy
Numpy was released in 2005 with the goal of bringing scientific computing to Python. <br>
It was based on Numeric and Numarray packages <br>
The strength lies its ability to work with multi-dimensional array objects. <br>

It uses those to supercharge its linear algebra capabilities: <br>
- BLAS (Basic Linear Algebra Subprograms) <br>
- LAPACK (Linear Algebra Package)

In [2]:
# Import numpy library
import numpy as np

## 1. Arrays, shape, size, data type

In [3]:
# Create 1d array, specify the datatype 'int32' and assign it to a
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
# Create 2d array and assign it to b
b = np.array([[9, 7, 5, 9 ], [4, 9, 2, 0]])
print(b)

[[9 7 5 9]
 [4 9 2 0]]


In [5]:
# Get dimension of a
a.ndim

1

In [6]:
# Get data type
a.dtype

dtype('int32')

In [7]:
# Get size in bytes
a.itemsize

4

In [8]:
# Get total size 
a.size

3

### Accessing and changing the specific elements in 2d array

In [9]:
# Create 2d array and assign it to a
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element, lets' say get 10
a[1, 2]

10

In [11]:
# Get a specific row, let's say the first row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column, let's say the third column
a[:, 2]

array([ 3, 10])

In [13]:
# Get 1,3,5, [sub-array, start:end:stepsize]
a[0, 0:-1:2]

array([1, 3, 5])

In [14]:
# Change the element, let's change 3 to 10
a[0, 2] = 10
print(a)

[[ 1  2 10  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Accessing and changing the specific elements in 3d array

In [15]:
# Create 3d array and assign it to b
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Get specific element, let's get 4
b[0, 1, 1]

4

##  2. Initializing Different Arrays (1s, 0s, full, random, etc...)

In [17]:
# All 0s matrix 2 by 3
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# All 1s matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
# Random numbers between 0-1
np.random.rand(5, 2)

array([[0.55335171, 0.67890855],
       [0.58494951, 0.47958742],
       [0.71486761, 0.28819607],
       [0.41715395, 0.62535582],
       [0.31396954, 0.15844067]])

In [20]:
# Random integer values between 0-3 with 3 by 3
np.random.randint(4, size=(3,3))

array([[0, 0, 1],
       [0, 0, 1],
       [2, 2, 0]])

In [21]:
# Identity matrix. All the diagonal elements are 1
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# Repeat each element of the array 3 times
arr = np.array([1,2,3])

r1 = np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


## 3. Basic Mathematics

In [23]:
# Addition
a =np.array([1,2,3])
a + 2

array([3, 4, 5])

In [24]:
# Subtraction
a -1

array([0, 1, 2])

In [25]:
# Multiplication
a * 3

array([3, 6, 9])

In [26]:
# Division
a / 2

array([0.5, 1. , 1.5])

In [27]:
# Exponentiation
a ** 2

array([1, 4, 9])

In [28]:
# Modulo
a % 2

array([1, 0, 1])

In [29]:
# Addition with other object
b = np.array([1,2,3])
a + b

array([2, 4, 6])

## 4. Linear Algebra

In [30]:
# Matrix multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [31]:
# Find the determinant. The matrix is invertible (has an inverse).
c = np.identity(3)
np.linalg.det(c)

1.0

## 5. Statistics 

In [32]:
# Create the array and call it stats
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# Show minimum from the array
np.min(stats)

1

In [34]:
# Show maximum from the array
np.max(stats, axis=1)

array([3, 6])

In [35]:
# Show mean from the array
np.mean(stats, axis=1)

array([2., 5.])

## 6. Reorganizing Arrays 

In [36]:
# Reshape the array to 2x2x2
before = np.array([[1,2,3,4], [5,6,7,8]])
before

after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
# Vertically Stack Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [40]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## 7. Load the data from a file 

In [ ]:
# Load the data.txt and  change it to int32
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

In [ ]:
# Load the data from csv 
data = np.loadtxt('filename.csv', delimiter=',')
print(data)

## 8. Indexing & Boolean Masking

In [ ]:
# Check the data which are more than 50 
filedata > 50